name: continuous-deployment
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'

jobs:
  continuous-deployment:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - name: Install dependencies
        run: pnpm install
      - name: Create Token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Run script disable security branch
        run: node src/disable-security-branch.js
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
      - name: Run script enable security branch
        if: always()
        run: node src/enable-security-branch.js
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
