name: continuous-deployment
on: [push]
jobs:
  delete-access-restrictions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install pnpm"
        run: "npm install -g pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run script
        run: node src/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
