name: VHC APP
on:
  push:
    branches: [test]
    paths-ignore:
      - '.github/**'

jobs:
  delete-access-restrictions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.9.0
      - name: Install dependencies
        run: pnpm install
      - name: Create Token
        id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Run script disable security branch
        run: node src/disable-security-branch.js
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
